version: '3.8'

services:
  ml-api:
    build:
      context: ./code/ml
    container_name: ad-flask
    ports:
      - "5001:5001"
    restart: unless-stopped

  backend:
    build:
      context: ./code/backend
    container_name: ad-maven
    ports:
      - "8080:8080"
    depends_on:
      - ml-api
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped

  frontend:
    build:
      context: ./code/frontend
    container_name: ad-react
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped